//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jQueryAjaxInAsp.NETMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class Registro
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Este campo es requerido.")]
        public string Nombre { get; set; }
        [DisplayName("Apellido Paterno")]
        [Required(ErrorMessage = "Este campo es requerido.")]
        public string ApellidoPaterno { get; set; }
        [DisplayName("Apellido Materno")]
        [Required(ErrorMessage = "Este campo es requerido.")]
        public string ApellidoMaterno { get; set; }
        [Required(ErrorMessage = "Este campo es requerido.")]
        public Nullable<int> Edad { get; set; }
        public string Foto { get; set; }

        [NotMapped]
        public HttpPostedFileBase CargarImagen { get; set; }

        public Registro()
        {
            Foto = "~/AppFiles/Imagenes/default2.png";
        }
    }
}